apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - infrastructure/cloudnative-pg/application.yaml
  
  # Applications
  - apps/dev/application.yaml
  - apps/prod/application.yaml

