{{- if .Values.argorollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argorollouts.name }}
  namespace: {{ .Values.global.argocdNamespace }}
  finalizers:
    - argocd.argoproj.io/resources-finalizer
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argorollouts.syncWave | quote }}
spec:
  project: {{ .Values.global.project }}
  
  source:
    repoURL: {{ .Values.argorollouts.source.repoURL }}
    targetRevision: {{ .Values.argorollouts.source.targetRevision }}
    path: {{ .Values.argorollouts.source.path }}
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argorollouts.destination.namespace }}
  
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal }}
      allowEmpty: {{ .Values.syncPolicy.automated.allowEmpty }}
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: {{ .Values.syncPolicy.retry.limit }}
      backoff:
        duration: {{ .Values.syncPolicy.retry.backoff.duration }}
        factor: {{ .Values.syncPolicy.retry.backoff.factor }}
        maxDuration: {{ .Values.syncPolicy.retry.backoff.maxDuration }}
{{- end }}

