apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saga-postgres-prod
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  
  source:
    repoURL: https://github.com/4bitlabs/saga.git
    targetRevision: main
    path: helm/postgres-chart
    helm:
      releaseName: saga-postgres-prod
      valueFiles:
        - values-prod.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: saga-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

